// This file was auto-generated by ML.NET Model Builder. 

using System;
using ConsoleAppTextTestAIML.Model;

namespace ConsoleAppTextTestAIML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput()
            {
                Email = @"Etikettendrucker Abrechnung funktioniert nicht.",
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual CategoryId with predicted CategoryId from sample data...\n\n");
            Console.WriteLine($"Email: {sampleData.Email}");
            Console.WriteLine($"\n\nPredicted CategoryId value {predictionResult.Prediction} \nPredicted CategoryId scores: [{String.Join(",", predictionResult.Score)}]\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
